admin: 김기범 # 실험자 이름 변경
seed: 42
train:
  model_name: klue/roberta-small
  batch_size: 32
  epoch: 100
  LR: 1e-5
  LossF: L1Loss
  optim: AdamW
  shuffle: True
  max_len: 160
use_data:
  - original data