admin: 김기범 # 실험자 이름 변경
seed: 42
train:
  model_name: 
  batch_size:
    - 16
    - 32
    - 64
  epoch: 100
  LR: 1e-5
  LossF: L1Loss
  optim: AdamW
use_data:
  - original data
  - BT
  - swap
save_path: None