admin: Kim GiBeom # 실험자 이름 변경
seed: 42
train:
  model_name: klue/roberta-small
  batch_size: 32
  epoch: 1
  LR: 0.0001
  LossF: L1Loss
  optim: AdamW
  shuffle: True
  max_len: 60
select_clean:
  - example
select_DP:
  - example