admin: KGB # 실험자 이름
patience: 5
seed: 42
train:
  model_name: monologg/koelectra-base-v3-discriminator # snunlp/KR-ELECTRA-discriminator
  batch_size: 32
  epoch: 100
  LR: 0.00002
  LossF: MSELoss # CosineEmbeddingLoss
  optim: AdamW
  # LR_scheduler : Step
  shuffle: True
  max_len: 100
select_clean:
  # - remove_consonant
  # - remove_special_word
  # - spellcheck
  - process_eng
select_DA:
  - create_5
  - swap_sentence
