admin: KGB # 실험자 이름
patience: 5
seed: 42
train:
  model_name: monologg/koelectra-base-v3-discriminator # snunlp/KR-ELECTRA-discriminator
  batch_size: 32
  epoch: 100
  LR: 0.00002
  LossF: MSELoss # CosineEmbeddingLoss
  optim: AdamW
  # LR_scheduler : Step
  shuffle: True
  max_len: 100
  uniform_train_data: False # train data를 uniform하게 만들고 싶다면 True
  uniform_max_len: 516 # train data에서 이 숫자를 초과하는 레이블은 undersampling, 미만인 레이블은 oversampling됩니다.
  uniform_max_duplicate: 3 # oversampling시 특정 데이터에 과적합되는걸 방지하기 위해서 이 숫자 이상 데이터를 복제하지 않습니다.
select_clean:
  # - remove_consonant
  # - remove_special_word
  # - spellcheck
  - process_eng
select_DA:
  - create_5
  - swap_sentence
