admin: KGB # 실험자 이름
seed: 42
train:
  model_name: beomi/kcbert-base
  batch_size: 64
  epoch: 100
  LR: 0.00001
  LossF: MSE
  optim: AdamW
  shuffle: True
  max_len: 200
df_split: True
select_clean:
  - example1
  - example2
  - example3
select_DA:
  - example1
  - example2
  - example3