admin: SE # 실험자 이름
patience: 5
seed: 42
train:
  model_name: snunlp/KR-ELECTRA-discriminator #monologg/koelectra-base-v3-discriminator
  batch_size: 32
  epoch: 100
  LR: 0.00001
  LossF: MSELoss
  optim: AdamW
  shuffle: True
  max_len: 120
select_clean:
  # - remove_special_word
  # - spellcheck
select_DA:
  - swap_sentence
  - create_5
