admin: JY # 실험자 이름
seed: 42
train:
  model_name: snunlp/KR-ELECTRA-discriminator
  batch_size: 32
  epoch: 100
  LR: 0.00001
  LossF: L1Loss
  optim: AdamW
  shuffle: True
  max_len: 200
select_clean:
  
select_DA:
  
focus_columns:
  - sentence_1
  - sentence_2