admin: KGB # 실험자 이름
patience: 5
seed: 42
train:
  model_name: snunlp/KR-ELECTRA-discriminator
  batch_size: 16
  epoch: 100
  LR: 0.00001
  LossF: MSELoss
  optim: AdamW
  shuffle: True
  max_len: 200
select_clean:
  - remove_special_word
select_DA:
  - swap_sentence
  # - random_deletion
