admin: SE # 실험자 이름
patience: 5
seed: 42
train:
  model_name: snunlp/KR-ELECTRA-discriminator
  batch_size: 32
  epoch: 100
  LR: 0.00001
  LossF: MSELoss #CosineEmbeddingLoss
  optim: AdamW
  # LR_scheduler : Step
  shuffle: True
  max_len: 140
select_clean:
  # - remove_special_word
  - process_eng
select_DA:
  - create_5_1
  - swap_sentence
  # - random_deletion
